workflows:
  flutter-app:
    name: Build Flutter App for iOS & Android
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ~/.gradle
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --debug
      - name: Build iOS Simulator
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/ios/iphonesimulator/*.app
